# Generated by Django 2.2.7 on 2020-02-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200207_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='picture',
            field=models.ImageField(blank=True, upload_to='quiz_pictures'),
        ),
    ]
