# Generated by Django 2.2.7 on 2020-02-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='picture',
        ),
    ]
