# Generated by Django 2.2.7 on 2020-02-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads1/%Y/%m/%d', verbose_name='Picture'),
        ),
    ]
