# Generated by Django 2.2.7 on 2020-02-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_quiz_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='figure',
        ),
        migrations.AddField(
            model_name='quiz',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Figure'),
        ),
    ]
