# Generated by Django 2.2.7 on 2020-02-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200209_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='draft',
        ),
    ]
