# Generated by Django 2.2.7 on 2020-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200210_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='draft',
            field=models.ImageField(blank=True, null=True, upload_to='uploadquiz', verbose_name='Draft'),
        ),
    ]
