# Generated by Django 2.2.7 on 2020-02-11 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20200210_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='Tên Môn', max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Giải Thích', max_length=2000, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answers_at_end',
            field=models.BooleanField(default=False, help_text='Đáp án sẽ hiện sau khi bài làm hoàn thành', verbose_name='Answers at end'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='draft',
            field=models.BooleanField(blank=True, default=False, help_text='Bản nháp', verbose_name='Draft'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_paper',
            field=models.BooleanField(default=False, help_text='Nếu có, kết quả của mỗi lần làm bài của người dùng sẽ được lưu trữ. Nên đánh dấu.', verbose_name='Exam Paper'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fail_text',
            field=models.TextField(blank=True, help_text='Hiển thị khi người dùng trượt', verbose_name='Fail Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Số câu trong 1 trang', null=True, verbose_name='Max Questions'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Tỷ lệ % cần thiết để vượt qua kỳ thi', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text='Đảo câu hỏi', verbose_name='Random Order'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='single_attempt',
            field=models.BooleanField(default=False, help_text='Chỉ cho phép người dùng làm bài', verbose_name='Single Attempt'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='success_text',
            field=models.TextField(blank=True, help_text='Hiển thị sau khi người dùng vượt qua bài thi', verbose_name='Success Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(help_text='Chữ hoặc số bất kỳ', max_length=60, verbose_name='user friendly url'),
        ),
    ]
