# Generated by Django 2.2.7 on 2020-02-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20180727_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Nhập câu hỏi mà bạn muốn hiển thị', max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Đây là câu trả lời đúng', verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], help_text='Thứ tự các tùy chọn trả lời được hiển thị cho người dùng', max_length=30, null=True, verbose_name='Answer Order'),
        ),
    ]
